spring:
  datasource:
    url: jdbc:h2:./appdb
    username: jk
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true

  h2:
    console:
      enabled: true
